In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2024-12-31 16:08:08.147521: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1735682888.245056    7887 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1735682888.273712    7887 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-31 16:08:08.519867: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.18.0


In [2]:
import tensorflow as tf

devices = tf.config.list_physical_devices()
for device in devices:
    print(device)

PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')
PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


In [3]:
import tensorflow as tf
print("GPU Available: ", len(tf.config.list_physical_devices('GPU')) > 0)

GPU Available:  True


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/home/maxkaizo/miniconda3/envs/conda_tf_gpu311/lib/python3.11/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
I0000 00:00:1735682965.864032    7887 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3539 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.15573543, -0.3784565 , -0.14738669,  0.47043103,  0.36180714,
         0.16097991,  0.22140373, -0.60668606,  0.5555209 , -0.41579577]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.10505123, 0.06157501, 0.07758126, 0.1439036 , 0.12909128,
        0.10560361, 0.11218131, 0.04901011, 0.15668438, 0.05931824]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.2480628)

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10


I0000 00:00:1735683052.430763    8188 service.cc:148] XLA service 0x7fe3f40038a0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1735683052.431444    8188 service.cc:156]   StreamExecutor device (0): NVIDIA GeForce RTX 4050 Laptop GPU, Compute Capability 8.9
2024-12-31 16:10:52.472339: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1735683052.552814    8188 cuda_dnn.cc:529] Loaded cuDNN version 90300


  57/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.4851 - loss: 1.7192

I0000 00:00:1735683053.600727    8188 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.8622 - loss: 0.4830
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9556 - loss: 0.1520
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9657 - loss: 0.1122
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9726 - loss: 0.0855
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9758 - loss: 0.0750
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9792 - loss: 0.0663
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9813 - loss: 0.0574
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9850 - loss: 0.0481
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9853 - loss: 0.0461
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9855 - loss: 0.0426


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

2024-12-31 16:11:42.390590: I external/local_xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:397] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_34', 4 bytes spill stores, 4 bytes spill loads



313/313 - 4s - 14ms/step - accuracy: 0.9779 - loss: 0.0762


[0.07623110711574554, 0.9779000282287598]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.1865072e-10, 7.3541710e-13, 3.5549718e-08, 8.7212484e-06,
        1.9175274e-14, 4.2167865e-09, 7.0784782e-18, 9.9998724e-01,
        4.7445953e-10, 4.0242485e-06],
       [7.7389721e-09, 3.7351795e-04, 9.9962556e-01, 8.1869507e-07,
        6.8770665e-21, 5.0400351e-09, 1.6326484e-11, 8.9400959e-17,
        1.5096260e-09, 2.7063890e-17],
       [6.0830796e-10, 9.9983680e-01, 3.1593506e-06, 1.7165014e-07,
        1.7146552e-06, 1.7105068e-08, 1.4546691e-06, 1.3367624e-04,
        2.3006027e-05, 2.8026056e-10],
       [9.9998784e-01, 9.0728709e-12, 1.2004311e-05, 3.7342871e-09,
        1.2643137e-10, 7.7956983e-09, 6.2146242e-08, 1.7672196e-08,
        4.1679819e-12, 2.4113323e-08],
       [3.0385692e-08, 4.1674868e-14, 9.5573256e-09, 2.1308272e-10,
        9.9900275e-01, 1.1264355e-08, 3.0259439e-08, 3.6911858e-06,
        4.9620978e-09, 9.9352631e-04]], dtype=float32)>